ui/package-lock.json, ui/package.json
Process is not defined error:
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined"
Added comments in package.json according to practices here: 
https://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install
=> [BUG FIX] fix process is not defined error.

.circleci/config.yml, Makefile
* Add make file for building and testing Daml templates
* Add build and testing job in circle ci
=> Add Makefile for Template Build & Testing

ui/public/index.html, ui/src/App.tsx, ui/src/components/PendingSwapRow/PendingSwapRow.tsx, ui/src/components/Prompts/Prompt.tsx, ui/src/components/TopAppBar/TopAppBar.tsx, ui/src/providers/ContractsProvider.tsx, ui/src/tabContents/IssuedByMeTab.tsx
* Use card for the prompts so that when in dark mode, text is readable
* Dark mode not completed yet
=> adjust colors on prompts.

ui/src/App.tsx, ui/src/components/Prompts/Prompt.tsx, ui/src/components/SideMenuMobile.tsx/SideMenuMobile.tsx, ui/src/components/TopAppBar/TopAppBar.tsx, ui/src/platform/platform.ts
* add util to check for platform (eg, mobile or desktop)
* Add sliding drawer for if mobile
=>  add check for platform.

ui/src/components/AssetAccountRow/AssetAccountRow.tsx, ui/src/components/AssetAccountRowNarrow/AssetAccountRowNarrow.tsx, ui/src/components/AssetDetailsPopupContent/AssetDetailsPopupContent.tsx, ui/src/components/PopUp/PopUp.tsx, ui/src/components/TopAppBar/TopAppBar.tsx, ui/src/featureFlags.ts, ui/src/providers/ContractsProvider.tsx, ui/src/tabContents/IssuedByMeTab.tsx, ui/src/tabContents/OwnedByMeTab.tsx
=> Mobile cards

ui/package.json, ui/src/components/AssetAccountRowNarrow/AssetAccountRowNarrow.tsx, ui/src/components/CreateAccountForm/CreateAccountForm.tsx, ui/src/components/IssueToSelfForm/IssueToSelfForm.tsx, ui/src/components/PendingAssetInviteRowNarrow/PendingAssetInviteRowNarrow.tsx, ui/src/components/PendingSwapRowNarrow/PendingSwapRowNarrow.tsx, ui/src/components/SendRowContents/SendRowContents.tsx
* make 'mint' to 'issue'
* Fix expand form in the issued by me tab
=> Fix spacing

ui/IssueToSelfSuccess/IssueToSelfSuccess.tsx, ui/src/components/AirdropForm/AirdropForm.tsx, ui/src/components/CreateAccountForm/CreateAccountForm.tsx, ui/src/components/CreateAccountPopupContent/CreateAccountPopupContent.tsx, ui/src/components/CreateAssetAccountSteps/CreateAssetAccountSteps.tsx, ui/src/components/InviteForm/InviteForm.tsx, ui/src/components/InviteNewAssetOwnerForm/InviteNewAssetOwnerForm.tsx, ui/src/components/IssueOrAirdropForm/IssueOrAirdropForm.tsx, ui/src/components/IssueToSelfForm/IssueToSelfForm.tsx, ui/src/components/PopUp/PopUp.tsx, ui/src/components/SendForm/SendForm.tsx, ui/src/components/SideMenu/SideMenu.tsx, ui/src/components/SwapForm/SwapForm.tsx, ui/src/components/TopAppBar/TopAppBar.tsx, ui/src/pages/CreateAssetAccountPage.tsx, ui/src/pages/MyActiveAccounts.tsx, ui/src/pages/Pages.tsx, ui/src/pages/PendingActivitiesPage.tsx, ui/src/tabContents/IssuedByMeTab.tsx
* includes the beginnings of adding steps
* fixed mobile margins
=> fix margin for mobile for the tabs.

ui/src/components/SendForm/SendForm.tsx, ui/src/components/SendPopupContent/SendPopupContent.tsx
* add total balance of asset when sending
=>  add balance.

ui/src/components/AssetAccountRow/AssetAccountRow.tsx, ui/src/components/FloatingBackButton/FloatingBackButton.tsx, ui/src/components/SendForm/SendForm.tsx, ui/src/ledgerHooks/ledgerHooks.ts, ui/src/pages/AssetProfilePage.tsx, ui/src/pages/IssueAirdropPage.tsx, ui/src/pages/Pages.tsx, ui/src/pages/SendPage.tsx, ui/src/tabContents/OwnedByMeTab.tsx
* connect send functionality with Daml
=> Fix asset details

ui/src/components/AssetDetails/AssetDetails.tsx, ui/src/components/InviteNewAssetOwnerForm/InviteNewAssetOwnerForm.tsx, ui/src/components/PendingActivities/PendingActivities.tsx, ui/src/components/PendingRowContents/PendingRowContents.tsx, ui/src/ledgerHooks/ledgerHooks.ts, ui/src/pages/AssetInvitePage.tsx, ui/src/pages/PendingActivityDetailsPage/PendingActivityDetailsPage.tsx, ui/src/pages/PendingAssetInviteDetailsPage.tsx, ui/src/pages/PendingSendDetailsPage.tsx, ui/src/pages/PendingSwapDetailsPage.tsx
=> Add invite

README.md, ui/src/components/AssetAccountRow/AssetAccountRow.tsx, ui/src/components/SwapForm/SwapForm.tsx, ui/src/ledgerHooks/ledgerHooks.ts, ui/src/pages/AssetProfilePage.tsx, ui/src/pages/SwapPage.tsx
* add propose swap feature. pending accepting swap / settle swap.
=>  add propse swap feature.

package-lock.json, ui/.eslintrc.json, ui/package-lock.json, ui/package.json, ui/src/ledgerHooks/ledgerHooks.ts, ui/src/pages/AccountInvitePage.tsx, ui/src/pages/AssetProfilePage.tsx
* added eslint
* removed a lot of whitespaces
=>  add eslint.

ui/src/components/AssetAccountRow/AssetAccountRow.tsx, ui/src/components/IssueSuccess/IssueSuccess.tsx, ui/src/components/PendingAccountInviteRow/PendingAccountInviteRow.tsx, ui/src/components/PendingSwapRow/PendingSwapRow.tsx, ui/src/components/PendingTransferRow/PendingTransferRow.tsx, ui/src/pages/MyActiveAccounts.tsx, ui/src/pages/PendingSendDetailsPage.tsx
* remove arrows in the pending row because adding the click functions is too complicated and not elegant.
=>  remove buttons, add right arrow.

README.md
* notes to make the ref app a better and more supported learning experience
=>  add notes to read me

ui/src/components/GettingStartedMessage/GettingStarted.tsx, ui/src/components/WelcomeMessage/WelcomeMessage.tsx
* adding the getting started text
=> Add new getting started

.gitignore, daml.yaml, wallet/ui/src/App.tsx, wallet/ui/src/index.tsx
* add DamlHub react library
* add damlhub provider 
* fix gitignore
=> add daml.yaml to root.

.gitignore, wallet/ui/src/components/InviteNewAssetOwnerForm/InviteNewAssetOwnerForm.tsx, wallet/ui/src/components/SwapForm/SwapForm.tsx, wallet/ui/src/pages/LoginPage.tsx
* add a default paste for the useradmin party
=> Default counter button

Concepts.md, UTXO.md, wallet/ui/src/components/CreateAccountForm/CreateAccountForm.tsx, wallet/ui/src/components/GettingStartedMessage/GettingStarted.tsx, wallet/ui/src/components/TopAppBar/TopAppBar.tsx, wallet/ui/src/components/WelcomeMessage/WelcomeMessage.tsx
* implement carrie's instructions
* Implement jennifer's more succinct way of describing party ID
=> Add instructions

Makefile, main/Account/daml/Test.daml, main/Asset/daml/Test.daml, main/Tests/daml/Test.daml
* Asset specific test
* Split up account tests for readability
Account Tests:
accountBalance_test: Script ()
dupe_account_test  : Script ()
account_reshare_test  : Script ()
account_airdrop_test: Script ()
transfer_test: Script ()
transfer_privacy_test: Script ()
dupe_account_invite_test: Script ()
account_recipient_mismatch_test: Script ()
trade_test: Script ()
We get an individual test script result table results for each test scenario which makes reading the results from the script easier. 
It's a cleaner starting state as well, for each scenario we have a clean starting state 
downside is that it is more verbose in code, but readability > brevity.
Output looks like 
```
daml/Test.daml:setupParties: ok, 0 active contracts, 0 transactions.
daml/Test.daml:accountBalance_test: ok, 3 …
```
=> Split Tests

AtomicSwap.md
Add the article on atomic swap workflow
=> Add AtomicSwap.md

README.md, main/Account/daml/Account.daml, triggers/daml/AcceptSwapTrigger.daml, triggers/daml/SendAssetHoldingAccountInviteTrigger.daml
* ensure the admin will always have enough balance to swap with
*
=> Ensure adequate balance to swap with

main/Account/daml/Account.daml
Changed explicit binding of Asset contract fields to namesake local variables in Issue_Asset choice to implicit, which is idiomatic in Daml.
=> Update Issue_Asset choice in Account.daml
